.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Daniel Patrick Abrecht <deb@danielabrecht.ch>,
.\"
.TH console-keyboard-basic 1 "August 11 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
console-keyboard-basic \- A very basic console keyboard.
.SH SYNOPSIS
.B cosole-keyboard-basic
.SH DESCRIPTION
This is a very basic proof of concept console-keyboard.
While this can be started on it's own, it isn't all that useful if it is.
The intended way to use this console-keyboard is using a console-keyboard-multiplexer.
